---
version: 0.2
env:
  parameter-store:
    GITHUB_TOKEN: '/github-bot/github/token'
    SECRET: '/github-bot/secret'
phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
    commands:
    - 'pip install yamllint==1.16.0'
    - 'pip install awscli==1.16.213'
    - 'pip install cfn-lint==0.23.1'
  pre_build:
    commands:
    - 'npm install'
    - 'npm test'
    - 'npm prune --production'
    - 'cd lambda-src'
    - 'mv config.example.json config.json'
    - 'sed -i "s:GITHUB_TOKEN:${GITHUB_TOKEN}:g" config.json'
    - 'sed -i "s:SECRET:${SECRET}:g" config.json'
    - 'npm install'
    - 'npm test'
    - 'npm prune --production'
    - 'cd ..'
  build:
    commands:
    - 'aws cloudformation package --template-file template.yml --s3-bucket ${BUCKET_NAME} --output-template-file packaged.yml'
    - 'aws cloudformation deploy --template-file packaged.yml --stack-name github-bot --capabilities CAPABILITY_IAM'
